'use client';

import React from 'react';
import { motion } from 'framer-motion';
import {
    ArrowLeft,
    AlertTriangle,
    BookOpen,
    Cpu,
    Lock,
    BarChart3,
    FlaskConical,
    Heart,
    Scale,
    CheckCircle
} from 'lucide-react';
import Footer from './Footer';

interface DisclaimerPageProps {
    setCurrentPage: (page: string) => void;
}

export default function DisclaimerPage({ setCurrentPage }: DisclaimerPageProps) {
    const disclaimerItems = [
        {
            icon: AlertTriangle,
            title: 'Not for Emergencies',
            description: 'Do not use this tool for emergency situations. If experiencing chest pain, severe shortness of breath, or other acute symptoms, call emergency services immediately.',
            isDanger: true,
        },
        {
            icon: BookOpen,
            title: 'Educational Use Only',
            description: 'This tool is for informational purposes only and does not replace professional medical advice, diagnosis, or treatment.',
        },
        {
            icon: Cpu,
            title: 'AI Model Limitations',
            description: 'Predictions are generated using machine learning based on historical data and may involve bias or error. Results should be interpreted cautiously.',
        },
        {
            icon: Lock,
            title: 'Data Privacy',
            description: 'User data is processed securely following industry standard privacy practices. No personal information is stored without consent.',
        },
        {
            icon: BarChart3,
            title: 'Prediction Confidence',
            description: 'Confidence scores indicate statistical likelihood, not guaranteed outcomes. Interpret results alongside professional medical evaluation.',
        },
        {
            icon: FlaskConical,
            title: 'Clinical Validation',
            description: 'The model has been train-validated on large datasets but is not a substitute for clinical examination and diagnostic testing.',
        },
        {
            icon: Heart,
            title: 'Limited Conditions',
            description: 'The system considers limited cardiovascular indicators and may not cover rare conditions or complex medical histories.',
        },
        {
            icon: Scale,
            title: 'Liability',
            description: 'The developers are not responsible for medical decisions or outcomes based on this tool. Always consult qualified healthcare professionals.',
        },
        {
            icon: CheckCircle,
            title: 'User Consent',
            description: 'By continuing, you acknowledge and accept these limitations and agree to use this tool responsibly for educational purposes only.',
        },
    ];

    return (
        <div className="min-h-screen pt-28 bg-[#0a0a0a]">
            <div className="max-w-5xl mx-auto px-6 pb-16">
                {/* Back Button */}
                <motion.div
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                >
                    <motion.button
                        whileHover={{ scale: 1.02 }}
                        whileTap={{ scale: 0.98 }}
                        onClick={() => setCurrentPage('home')}
                        className="inline-flex items-center gap-2 px-4 py-2 mb-8 text-sm font-medium bg-zinc-800 border border-zinc-700 text-white rounded-lg hover:bg-zinc-700 transition-colors"
                    >
                        <ArrowLeft className="w-4 h-4" />
                        Back to Home
                    </motion.button>
                </motion.div>

                {/* Title */}
                <motion.div
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: 0.1 }}
                >
                    <h1 className="text-4xl font-bold text-white mb-4">Disclaimer</h1>
                    <p className="text-zinc-400 text-lg mb-8 max-w-2xl">
                        This prediction is generated by a machine learning model and is not a medical diagnosis.
                        Please consult a physician for expert medical evaluation and treatment.
                    </p>
                </motion.div>

                {/* Warning Notice */}
                <motion.div
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: 0.2 }}
                >
                    <div className="p-5 bg-yellow-500/10 border border-yellow-500/30 rounded-xl mb-8">
                        <p className="text-yellow-400 text-sm leading-relaxed">
                            <strong>⚠️ Important:</strong> This cardiovascular risk assessment tool uses AI-trained algorithms to provide educational insights into heart health.
                            Please read all disclaimers carefully before using this service.
                        </p>
                    </div>
                </motion.div>

                {/* Disclaimer Items */}
                <div className="space-y-4 mb-12">
                    {disclaimerItems.map((item, index) => (
                        <motion.div
                            key={item.title}
                            initial={{ opacity: 0, x: -20 }}
                            animate={{ opacity: 1, x: 0 }}
                            transition={{ delay: 0.05 * index }}
                            className={`
                flex gap-4 p-5 rounded-xl border transition-all duration-200
                ${item.isDanger
                                    ? 'bg-red-500/5 border-l-4 border-l-red-500 border-red-500/20'
                                    : 'bg-zinc-900 border-zinc-800 hover:bg-zinc-800/80 hover:border-zinc-700 hover:translate-x-1'
                                }
              `}
                        >
                            <div className={`
                w-10 h-10 rounded-lg flex items-center justify-center flex-shrink-0
                ${item.isDanger ? 'bg-red-500/20 text-red-400' : 'bg-blue-500/10 text-blue-400'}
              `}>
                                <item.icon className="w-5 h-5" />
                            </div>
                            <div>
                                <h3 className="font-semibold text-white mb-1">{item.title}</h3>
                                <p className="text-zinc-400 text-sm leading-relaxed">{item.description}</p>
                            </div>
                        </motion.div>
                    ))}
                </div>

                {/* Footer Note */}
                <motion.div
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                >
                    <div className="pt-6 border-t border-zinc-800">
                        <p className="text-zinc-500 text-sm">
                            <strong className="text-zinc-400">Last Updated:</strong> January 2025
                        </p>
                        <p className="text-zinc-500 text-sm mt-1">
                            For questions or concerns, please contact our support team.
                        </p>
                    </div>
                </motion.div>
            </div>

            <Footer setCurrentPage={setCurrentPage} />
        </div>
    );
}
